Imports System.Xml.Serialization


'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


' 
' This source code was auto-generated by xsd, Version=4.0.30319.1.
' 


''' <remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")> _
<System.SerializableAttribute()> _
<System.Diagnostics.DebuggerStepThroughAttribute()> _
<System.ComponentModel.DesignerCategoryAttribute("code")> _
<System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
<System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
Partial Public Class DataApplication

    Private databaseField As DataApplicationDatabase()

    Private queriesField As DataApplicationQuery()

    ''' <remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Database")> _
    Public Property Database() As DataApplicationDatabase()
        Get
            Return Me.databaseField
        End Get
        Set(ByVal value As DataApplicationDatabase())
            Me.databaseField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Query", IsNullable:=False)> _
    Public Property Queries() As DataApplicationQuery()
        Get
            Return Me.queriesField
        End Get
        Set(ByVal value As DataApplicationQuery())
            Me.queriesField = value
        End Set
    End Property
End Class

''' <remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")> _
<System.SerializableAttribute()> _
<System.Diagnostics.DebuggerStepThroughAttribute()> _
<System.ComponentModel.DesignerCategoryAttribute("code")> _
<System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class DataApplicationDatabase

    Private idField As String

    Private databaseField As String

    Private passwordField As String

    Private serverAddressField As String

    Private userNameField As String

    Private databaseTypeField As String

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property ID() As String
        Get
            Return Me.idField
        End Get
        Set(ByVal value As String)
            Me.idField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Database() As String
        Get
            Return Me.databaseField
        End Get
        Set(ByVal value As String)
            Me.databaseField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set(ByVal value As String)
            Me.passwordField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property ServerAddress() As String
        Get
            Return Me.serverAddressField
        End Get
        Set(ByVal value As String)
            Me.serverAddressField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property UserName() As String
        Get
            Return Me.userNameField
        End Get
        Set(ByVal value As String)
            Me.userNameField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property DatabaseType() As String
        Get
            Return Me.databaseTypeField
        End Get
        Set(ByVal value As String)
            Me.databaseTypeField = value
        End Set
    End Property
End Class

''' <remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")> _
<System.SerializableAttribute()> _
<System.Diagnostics.DebuggerStepThroughAttribute()> _
<System.ComponentModel.DesignerCategoryAttribute("code")> _
<System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class DataApplicationQuery

    Private nameField As String

    Private databaseIDField As String

    Private valueField As String

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set(ByVal value As String)
            Me.nameField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property DatabaseID() As String
        Get
            Return Me.databaseIDField
        End Get
        Set(ByVal value As String)
            Me.databaseIDField = value
        End Set
    End Property

    ''' <remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set(ByVal value As String)
            Me.valueField = value
        End Set
    End Property
End Class

'=======================================================
'Service provided by Telerik (www.telerik.com)
'Conversion powered by NRefactory.
'Twitter: @telerik
'Facebook: facebook.com/telerik
'=======================================================
